<a href="https://colab.research.google.com/github/beherasantosh/pytorch_sample/blob/master/00_firstnotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.11.0+cpu


# Introduction to **Tensors**

## Creating Sensons

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [9]:
t1 = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
t1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
t1[0,1,2]

tensor(6)

### Random numbers

In [11]:
randrom_tensor = torch.rand(2, 3,4)
randrom_tensor

tensor([[[0.6199, 0.1066, 0.3940, 0.6876],
         [0.3854, 0.2483, 0.4227, 0.5849],
         [0.4365, 0.8262, 0.1757, 0.8345]],

        [[0.5443, 0.2599, 0.1929, 0.7247],
         [0.9846, 0.4755, 0.2795, 0.8969],
         [0.9611, 0.0737, 0.8431, 0.2403]]])

In [12]:
randrom_tensor.ndim

3

In [13]:
randrom_tensor.shape

torch.Size([2, 3, 4])

In [14]:
zero_random = torch.zeros(size=(3,5))
zero_random

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [18]:
ones = torch.ones(2,3)
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

### Create range

In [30]:
step_range = torch.arange(start=1, end=10, step= 1)
step_range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
zeros_sample = torch.zeros_like(input= step_range)
zeros_sample.ndim, zeros_sample.shape

(1, torch.Size([9]))

In [48]:
simpel1 = torch.tensor([3, 5])
simpel1, simpel1.device, simpel1.size(), simpel1.shape, simpel1.dtype

(tensor([3, 5]),
 device(type='cpu'),
 torch.Size([2]),
 torch.Size([2]),
 torch.int64)

## Tensor Operation

In [51]:
t1 = torch.tensor([1,2,3])
t1 + 10

tensor([11, 12, 13])

In [52]:
t1 * 12

tensor([12, 24, 36])

## Min, Max, Mean, Sum, Aggregation

In [54]:
x = torch.arange(1, 100, 5)
x

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [59]:
x.dtype

torch.int64

In [60]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(48.5000), tensor(48.5000))