<a href="https://colab.research.google.com/github/beherasantosh/pytorch_sample/blob/master/00_firstnotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.11.0+cpu


# Introduction to **Tensors**

## Creating Sensons

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [9]:
t1 = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
t1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
t1[0,1,2]

tensor(6)

### Random numbers

In [11]:
randrom_tensor = torch.rand(2, 3,4)
randrom_tensor

tensor([[[0.6199, 0.1066, 0.3940, 0.6876],
         [0.3854, 0.2483, 0.4227, 0.5849],
         [0.4365, 0.8262, 0.1757, 0.8345]],

        [[0.5443, 0.2599, 0.1929, 0.7247],
         [0.9846, 0.4755, 0.2795, 0.8969],
         [0.9611, 0.0737, 0.8431, 0.2403]]])

In [12]:
randrom_tensor.ndim

3

In [13]:
randrom_tensor.shape

torch.Size([2, 3, 4])

In [14]:
zero_random = torch.zeros(size=(3,5))
zero_random

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [18]:
ones = torch.ones(2,3)
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)